baseurl = "https://lanycrost.github.io"
title = "Khachatur Ashotyan's Home in the NET | lanycrost | Let's Rock!"
languageCode = "en-us"
publishDir = "docs"

[menu]
  [[menu.header]]
    name = "stories"
    weight = 0
    url = "https://medium.com/@lanycrost"
  [[menu.header]]
    name = "~/works"
    identifier = "works"
    weight = 1
    url = "#"
  [[menu.header]]
    Name = "WHOIS-Server"
    parent = "works"
    URL = "https://github.com/lanycrost/whois-server"
    Weight = 1.0
  [[menu.header]]
    name = "about"
    weight = 2
    url = "/about"

[params]
  GithubID = "lanycrost"
  TwitterID = "lanycrost"
  LinkedInID = "lanycrost"
  FacebookID = "lanycrost"
  HeaderUsername = "me"
  HeaderHostname = "lanycrost.net"
  InstagramID = "lanycrost"
  CodeStatsID = "lanycrost"
  WeChallID = "lanycrost"
